import { Injectable, Logger } from "@nestjs/common";
import { Cron, CronExpression } from "@nestjs/schedule";
import { PrismaService } from "../../prisma/prisma.service";

@Injectable()
export class RecurringTasksCron {
  private readonly logger = new Logger(RecurringTasksCron.name);

  constructor(private readonly prisma: PrismaService) {}

  // Menjalankan cron setiap hari jam 00:00 (tengah malam)
  @Cron(CronExpression.EVERY_DAY_AT_MIDNIGHT)
  async handleDailyTasks() {
    this.logger.log("Menjalankan cron untuk RecurringTask [DAILY]...");

    try {
      // Ambil tugas yang frekuensinya harian
      const dailyTasks = await this.prisma.recurringTask.findMany({
        where: { frequency: "DAILY" },
        include: { group: true },
      });

      let count = 0;
      for (const rt of dailyTasks) {
        // TODO: Resolve which project to create the task in. A group can have multiple projects.
        // await this.prisma.task.create({
        //   data: {
        //     title: rt.name,
        //     // projectId: rt.group.projectId, // This is no longer valid
        //     groupId: rt.groupId,
        //     assigneeId: rt.assignTo,
        //     status: "TODO",
        //     priorityLevel: 1, // Default prioritas
        //     taskActivity: `Auto-generated by System (Daily) pada ${new Date().toISOString()}`,
        //   },
        // });
        count++;
      }

      if (count > 0) {
        this.logger.log(`Berhasil men-generate ${count} task harian.`);
      }
    } catch (error) {
      this.logger.error("Gagal men-generate task harian", error);
    }
  }

  // Menjalankan cron setiap minggu (contoh: Senin jam 00:00)
  @Cron("0 0 * * 1")
  async handleWeeklyTasks() {
    this.logger.log("Menjalankan cron untuk RecurringTask [WEEKLY]...");

    try {
      // Ambil tugas yang frekuensinya mingguan
      const weeklyTasks = await this.prisma.recurringTask.findMany({
        where: { frequency: "WEEKLY" },
        include: { group: true },
      });

      let count = 0;
      for (const rt of weeklyTasks) {
        // TODO: Resolve which project to create the task in. A group can have multiple projects.
        // await this.prisma.task.create({
        //   data: {
        //     title: rt.name,
        //     // projectId: rt.group.projectId, // This is no longer valid
        //     groupId: rt.groupId,
        //     assigneeId: rt.assignTo,
        //     status: "TODO",
        //     priorityLevel: 2,
        //     taskActivity: `Auto-generated by System (Weekly) pada ${new
        //       .toISOString()}`,
        //   },
        // });
        count++;
      }

      if (count > 0) {
        this.logger.log(`Berhasil men-generate ${count} task mingguan.`);
      }
    } catch (error) {
      this.logger.error("Gagal men-generate task mingguan", error);
    }
  }
}
